apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-elasticsearch-service
spec:
  type: NodePort
  selector:
    app: mall-elasticsearch
  ports:
    - nodePort: 30093
      port: 18093
      targetPort: 18093
      protocol: TCP
