apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-captcha-service
spec:
  type: NodePort
  selector:
    app: mall-captcha
  ports:
    - nodePort: 30077
      port: 18077
      targetPort: 18077
      protocol: TCP
