spring:
  # 微服务配置
  cloud:
    # Nacos 配置
    nacos:
      # Nacos 注册中心
      discovery:
        server-addr: 127.0.0.1:8848
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: 127.0.0.1:8858

# 雪花分布式ID生成器配置
snowflake:
  worker-id: 1
  datacenter-id: 1
