spring:
  profiles:
    active: dev
  # 微服务配置
  cloud:
    # SpringCloud Gateway 网关配置
    gateway:
      # 服务发现配置
      discovery:
        locator:
          # 使用微服务名称进行定位
          enabled: true
          # 设置服务名称为小写, 默认 false 为大写
          lower-case-service-id: true
      # 路由配置
      routes:
        # SpringSecurity 安全模块
        - id: mall-security
          uri: lb://mall-security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
        # 用户模块
        - id: mall-user
          uri: lb://mall-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        # 管理员模块
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        # MinIO 文件模块
        - id: mall-minio
          uri: lb://mall-minio
          predicates:
            - Path=/minio/**
          filters:
            - StripPrefix=1
        # FastDFS 文件模块
        - id: mall-fastdfs
          uri: lb://mall-fastdfs
          predicates:
            - Path=/fastdfs/**
          filters:
            - StripPrefix=1
        # ElasticSearch 搜索模块
        - id: mall-elasticsearch
          uri: lb://mall-elasticsearch
          predicates:
            - Path=/elasticsearch/**
          filters:
            - StripPrefix=1
        # Solr 搜索模块
        - id: mall-solr
          uri: lb://mall-solr
          predicates:
            - Path=/solr/**
          filters:
            - StripPrefix=1
        # 商品模块
        - id: mall-goods
          uri: lb://mall-goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
        # 订单模块
        - id: mall-order
          uri: lb://mall-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
  # 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取 RSA 公钥 (不要直接配置成安全模块的地址, 因为只能配置单个地址, 而安全模块会启动多个; 配置网关本身的地址, 使用网关转发请求)
          jwk-set-uri: http://127.0.0.1:${server.port}/security/key-pair/rsa/public-key

# 安全配置
secure:
  ignore-urls:
    - "/actuator/**"
    - "/security/**"
