spring:
  profiles:
    active: dev
  # 微服务配置
  cloud:
    # SpringCloud Gateway 网关配置
    gateway:
      # 服务发现配置
      discovery:
        locator:
          # 从注册中心自动获取微服务名称, 使用微服务名称作为路由id
          enabled: true
          # 微服务名称转换为小写
          lower-case-service-id: true
  # Spring Security 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取 RSA 公钥
          jwk-set-uri: http://127.0.0.1:${server.port}/mall-security/keypair/rsa

# 网关安全配置
secure:
  ignore-urls:
    - "/actuator/**"
    - "/mall-security/**"
