apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mall
  name: mall-foundation-deployment
  labels:
    name: mall-foundation-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mall-foundation
  template:
    metadata:
      namespace: mall
      name: mall-foundation-pod
      labels:
        app: mall-foundation
    spec:
      restartPolicy: Always
      containers:
        - name: mall-foundation-container
          image: 192.168.159.128:5000/mall/mall-foundation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 18084
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
