apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-foundation-service
spec:
  type: NodePort
  selector:
    app: mall-foundation
  ports:
    - nodePort: 30084
      port: 18084
      targetPort: 18084
      protocol: TCP
