apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-zuul-service
spec:
  type: NodePort
  selector:
    app: mall-zuul
  ports:
    - nodePort: 32003
      port: 8040
      targetPort: 8040
      protocol: TCP
