spring:
  profiles:
    active: dev
  # 允许同名 Bean 覆盖
  main:
    allow-bean-definition-overriding: true

# Feign 配置
feign:
  # Feign 远程方法调用开启 Sentinel 熔断限流
  sentinel:
    enabled: true

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 数据库表命名使用下划线分割
      table-underline: true

# LogBack 配置
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
