apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-user-service
spec:
  type: NodePort
  selector:
    app: mall-user
  ports:
    - nodePort: 30073
      port: 18073
      targetPort: 18073
      protocol: TCP
