apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-storage-service
spec:
  type: NodePort
  selector:
    app: mall-storage
  ports:
    - nodePort: 30083
      port: 18083
      targetPort: 18083
      protocol: TCP
