# Debezium 配置
debezium:
  # 数据源配置
  datasource:
    # Host
    host: host.docker.internal
    # Port
    port: 3306
    # 用户名
    username: root
    # 密码
    password: 123456
    # 监听的数据库
    database: mall_order
