spring:
  profiles:
    active: dev
  # 自动装配时排除 JDBC 数据源配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # 允许同名 Bean 覆盖
  main:
    allow-bean-definition-overriding: true

# Feign 配置
feign:
  # Feign 远程方法调用开启 Sentinel 熔断限流
  sentinel:
    enabled: true

# LogBack 配置
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
