spring:
  profiles:
    active: dev
  # 自动装配时排除 JDBC 数据源配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # 允许同名 Bean 覆盖
  main:
    allow-bean-definition-overriding: true

# Feign 配置
feign:
  # 开启 Hystrix
  hystrix:
    enabled: true

# Hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 超时熔断时间 10000 毫秒
            timeoutInMilliseconds: 10000
