spring:
  cloud:
    # Nacos 配置
    nacos:
      # 注册中心
      discovery:
        server-addr: http://127.0.0.1:8848

# ElasticSearch 配置
elastic-search:
  host: 127.0.0.1
  port: 9200

# RocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
