spring:
  profiles:
    active: nacos
  # 自动装配时排除以下配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# RSA 证书口令, 生成 RSA 证书文件 (jwt.jks) 时设置
rsa:
  credential:
    # 密钥库名称
    keystore: "jwt.jks"
    # 密钥库口令
    storepass: "123456"
    # 别名
    alias: "jwt"
    # 密钥口令
    keypass: "123456"
