apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-goods-service
spec:
  type: NodePort
  selector:
    app: mall-goods
  ports:
    - nodePort: 30081
      port: 18081
      targetPort: 18081
      protocol: TCP
