apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-swagger-service
spec:
  type: NodePort
  selector:
    app: mall-swagger
  ports:
    - nodePort: 30076
      port: 18076
      targetPort: 18076
      protocol: TCP
