apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-goodscenter-service
spec:
  type: NodePort
  selector:
    app: mall-goodscenter
  ports:
    - nodePort: 30063
      port: 18063
      targetPort: 18063
      protocol: TCP
