apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-merchant-service
spec:
  type: NodePort
  selector:
    app: mall-merchant
  ports:
    - nodePort: 30087
      port: 18087
      targetPort: 18087
      protocol: TCP
