apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-minio-service
spec:
  type: NodePort
  selector:
    app: mall-minio
  ports:
    - nodePort: 30091
      port: 18091
      targetPort: 18091
      protocol: TCP
