apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-config-service
spec:
  type: NodePort
  selector:
    app: mall-config
  ports:
    - nodePort: 32002
      port: 8888
      targetPort: 8888
      protocol: TCP
