apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mall
  name: mall-config-deployment
  labels:
    name: mall-config-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mall-config
  template:
    metadata:
      namespace: mall
      name: mall-config-pod
      labels:
        app: mall-config
    spec:
      restartPolicy: Always
      containers:
        - name: mall-config-container
          image: 192.168.159.128:5000/mall/mall-config:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
