apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-apiconsumer-service
spec:
  type: NodePort
  selector:
    app: mall-apiconsumer
  ports:
    - nodePort: 30062
      port: 18062
      targetPort: 18062
      protocol: TCP
