apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-clickhouse-service
spec:
  type: NodePort
  selector:
    app: mall-clickhouse
  ports:
    - nodePort: 30096
      port: 18096
      targetPort: 18096
      protocol: TCP
