spring:
  cloud:
    # Nacos 配置
    nacos:
      # 注册中心
      discovery:
        server-addr: http://127.0.0.1:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://127.0.0.1:18072/key/rsa/public'
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
