spring:
  profiles:
    active: dev
  cloud:
    # 网关配置
    gateway:
      # 服务发现配置
      discovery:
        locator:
          # 使用微服务名称进行定位
          enabled: true
          # 设置服务名称为小写, 默认 false 为大写
          lower-case-service-id: true
      # 路由配置
      routes:
        - id: mall-security-manage
          uri: lb://mall-security-manage
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
        - id: mall-goods
          uri: lb://mall-goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

# 白名单路径配置
secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/security/**"
