apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-review-service
spec:
  type: NodePort
  selector:
    app: mall-review
  ports:
    - nodePort: 30088
      port: 18088
      targetPort: 18088
      protocol: TCP
