spring:
  application:
    name: eureka-cluster-1

server:
  port: 8761

eureka:
  instance:
    hostname: cluster-1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://cluster-2:8762/eureka, http://cluster-3:8763/eureka
