server:
  port: 8761

spring:
  application:
    name: eureka-cluster
  profiles: node-1

eureka:
  instance:
    hostname: node-1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone:
        - http://node-2:8762/eureka
        - http://node-3:8763/eureka
