spring:
  application:
    name: eureka-cluster-3

server:
  port: 8763

eureka:
  instance:
    hostname: cluster-3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://cluster-1:8761/eureka, http://cluster-2:8762/eureka
