server:
  port: 8763

spring:
  application:
    name: eureka-cluster
  profiles: node-3

eureka:
  instance:
    hostname: node-3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone:
        - http://node-1:8761/eureka
        - http://node-2:8762/eureka
