spring:
  profiles:
    active: dev

# Feign 配置
feign:
  # Feign 远程方法调用开启 Sentinel 熔断限流
  sentinel:
    enabled: true

# LogBack 配置
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

# 雪花分布式ID生成器配置
snowflake:
  worker-id: 1
  datacenter-id: 1
