apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-opensearch-service
spec:
  type: NodePort
  selector:
    app: mall-opensearch
  ports:
    - nodePort: 30098
      port: 18098
      targetPort: 18098
      protocol: TCP
