spring:
  profiles:
    active: dev
  # 自动装配时排除 JDBC 数据源配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Canal 数据库监听配置 (监听表配置)
canal:
  # 以下表的数据变更发送到 RabbitMQ
  rabbit-table:
    - mall_admin.mall_role
    - mall_admin.mall_role_menu
  # 以下表的数据变更发送到 RocketMQ
  rocket-table:
    - mall_goods.mall_brand
    - mall_goods.mall_category
