spring:
  profiles:
    active: dev
  # 自动装配时排除 JDBC 数据源配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # 允许同名 Bean 覆盖
  main:
    allow-bean-definition-overriding: true

# Feign 配置
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  sentinel:
    enabled: true

# Actuator 服务健康监控监控配置
management:
  endpoints:
    web:
      exposure:
        # 开放所有 Actuator 端点
        include: "*"
  endpoint:
    health:
      # 显示详细信息
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.appcation.name}
    export:
      prometheus:
        enabled: true

# LogBack 配置
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
