spring:
  # 微服务配置
  cloud:
    # Nacos 配置
    nacos:
      # Nacos 注册中心
      discovery:
        server-addr: 127.0.0.1:8848
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: 127.0.0.1:8858

# ElasticSearch 配置
elastic-search:
  host: 127.0.0.1
  port: 9200

# RocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
