spring:
  # Redis 配置
  redis:
    host: 192.168.44.128
    port: 6379
    password: 123456
    database: 0
  # Kafka 配置
  kafka:
    # Kafka 生产者配置
    producer:
      # Kafka 服务端地址
      bootstrap-servers: 192.168.44.128:9092

# XXL-JOB 配置
xxl:
  job:
    # 调度中心配置
    admin:
      addresses: http://192.168.44.128:8001/xxl-job-admin
