spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.44.128:3306/mall_goods?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # Redis 配置
  redis:
    host: 192.168.44.128
    port: 6379
    password: 123456
    database: 0

# RocketMQ 配置
rocketmq:
  name-server: 192.168.44.128:9876
  # 生产者配置
  producer:
    # 默认生产者组
    group: ${spring.application.name}
