knife4j:
  cloud:
    enable: true
    routes:
      - name: mall-security
        uri: 192.168.44.128:18072
        location: /v2/api-docs
      - name: mall-user
        uri: 192.168.44.128:18073
        location: /v2/api-docs
      - name: mall-id
        uri: 192.168.44.128:18074
        location: /v2/api-docs
      - name: mall-goods
        uri: 192.168.44.128:18081
        location: /v2/api-docs
      - name: mall-order
        uri: 192.168.44.128:18082
        location: /v2/api-docs
      - name: mall-storage
        uri: 192.168.44.128:18083
        location: /v2/api-docs
      - name: mall-foundation
        uri: 192.168.44.128:18084
        location: /v2/api-docs
      - name: mall-manager
        uri: 192.168.44.128:18085
        location: /v2/api-docs
      - name: mall-member
        uri: 192.168.44.128:18086
        location: /v2/api-docs
      - name: mall-merchant
        uri: 192.168.44.128:18087
        location: /v2/api-docs
      - name: mall-minio
        uri: 192.168.44.128:18091
        location: /v2/api-docs
      - name: mall-fastdfs
        uri: 192.168.44.128:18092
        location: /v2/api-docs
      - name: mall-elasticsearch
        uri: 192.168.44.128:18093
        location: /v2/api-docs
      - name: mall-solr
        uri: 192.168.44.128:18094
        location: /v2/api-docs
      - name: mall-qiniu
        uri: 192.168.44.128:18095
        location: /v2/api-docs
      - name: mall-clickhouse
        uri: 192.168.44.128:18096
        location: /v2/api-docs
