spring:
  # 微服务配置
  cloud:
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: host.docker.internal:8858

# 雪花分布式ID生成器配置
snowflake:
  worker-id: 1
  datacenter-id: 1
