spring:
  # Spring Security 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:${server.port}/mall-security/jwk-set/rsa
  # Sleuth 配置
  sleuth:
    sampler:
      # 采样率 (1: 全部采集)
      probability: 1
      # 速率 (每秒接收的 trace 数量)
      rate: 10
  # Zipkin 配置
  zipkin:
    base-url: http://127.0.0.1:9411
