spring:
  # 微服务配置
  cloud:
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: host.docker.internal:8858

# ElasticSearch 配置
elastic-search:
  host: host.docker.internal
  port: 9200
  schema: http

# RocketMQ 配置
rocketmq:
  name-server: host.docker.internal:9876
