spring:
  # 微服务配置
  cloud:
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: 192.168.44.128:8858
  # Redis 配置
  redis:
    host: 192.168.44.128
    port: 6379
    password: 123456
    database: 0

# 验证码配置
captcha:
  # 业务接口配置
  service:
    # 业务实现类
    implementation: easyCaptchaServiceImpl
