spring:
  # 自动装配时排除 JDBC 数据源配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# MySQL Binlog Connector 数据库监听配置
binlog:
  # 监听的数据表
  table:
    - mall_user.mall_role_menu

# Logback 配置
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
