spring:
  # Redis 配置
  redis:
    host: host.docker.internal
    port: 6379
    password: 123456
    database: 0

# 分布式ID配置
id:
  # 雪花分布式ID生成器配置
  snowflake:
    worker-id: 0
    datacenter-id: 4
  # Redis 分布式ID生成器配置
  redis:
    worker-id: 0
    datacenter-id: 4
  # Redisson 分布式ID生成器配置
  redisson:
    worker-id: 0
    datacenter-id: 4
