spring:
  # Kafka 配置
  kafka:
    # Kafka 消费者配置
    consumer:
      # Kafka 服务端地址
      bootstrap-servers: 127.0.0.1:9092

# ElasticSearch 配置
elasticsearch:
  scheme: http
  host: 127.0.0.1
  port: 9200

# RocketMQ 配置
rocketmq:
  # RocketMQ 服务端地址
  name-server: 127.0.0.1:9876
  # 生产者配置
  producer:
    # 默认生产者组
    group: ${spring.application.name}
