spring:
  # 微服务配置
  cloud:
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: 192.168.159.128:8858
  # Spring Data 配置
  data:
    # Solr 配置
    solr:
      host: http://192.168.159.128:8983/solr
