spring:
  # 微服务配置
  cloud:
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: 127.0.0.1:8858

# XXL-JOB 配置
xxl:
  job:
    # 通讯令牌
    accessToken: default_token
    # 调度中心配置
    admin:
      addresses: http://127.0.0.1:8001/xxl-job-admin
    # 执行器配置
    executor:
      appname: ${spring.application.name}
      port: 28061
      logpath: logs/xxl-job/${xxl.job.executor.appname}
      logretentiondays: 10
