spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_goods?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0

# RocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
  # 生产者配置
  producer:
    # 默认生产者组
    group: ${spring.application.name}

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # dev 环境打印 SQL 到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
