spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/mall_goods?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 微服务配置
  cloud:
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: host.docker.internal:8858
  # Redis 配置
  redis:
    host: host.docker.internal
    port: 6379
    password: 123456
    database: 0

# RocketMQ 配置
rocketmq:
  name-server: host.docker.internal:9876
  producer:
    # 生产者组名
    group: GROUP-ES
