spring:
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  # Kafka 配置
  kafka:
    # Kafka 生产者配置
    producer:
      # Kafka 服务端地址
      bootstrap-servers: 127.0.0.1:9092

# XXL-JOB 配置
xxl:
  job:
    # 调度中心配置
    admin:
      addresses: http://127.0.0.1:8001/xxl-job-admin
