spring:
  # Kafka 配置
  kafka:
    # Kafka 生产者配置
    producer:
      # Kafka 服务端地址
      bootstrap-servers: host.docker.internal:9092

# XXL-JOB 配置
xxl:
  job:
    # 调度中心配置
    admin:
      addresses: http://host.docker.internal:8001/xxl-job-admin
