spring:
  # RabbitMQ 配置
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: cafe
    password: cafe
    virtual-host: /

# MySQL Binlog Connector 数据库监听配置
binlog:
  host: host.docker.internal
  port: 3306
  username: root
  password: 123456
  # MySQL 服务端唯一标识
  server-id: 1
