spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/mall_foundation?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# RocketMQ 配置
rocketmq:
  name-server: host.docker.internal:9876
  # 生产者配置
  producer:
    # 默认生产者组
    group: ${spring.application.name}
