spring:
  # Spring Security 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:${server.port}/mall-security/jwk-set/rsa
  # Sleuth 配置
  sleuth:
    enabled: true
    sampler:
      # 采样率 (1: 全部采集)
      probability: 1
      # 速率 (每秒接收的 trace 数量)
      rate: 10
  # Zipkin 配置
  zipkin:
    enabled: true
    base-url: http://host.docker.internal:9411
