spring:
  # RabbitMQ 配置
  rabbitmq:
    # 生产者是否确认消息成功投递到交换机: NONE 不确认; CORRELATED 异步等待回调结果; SIMPLE 同步等待回调结果
    publisher-confirm-type: CORRELATED
    # 消息无法到达队列时是否退回给生产者
    publisher-returns: true

# Canal 数据库监听配置
canal:
  # 订阅的数据表
  subscribe-table: mall_.*\..*
  # 推送至 RabbitMQ 的数据表
  rabbitmq-table:
    - mall_user.mall_role_resource
  # 推送至 RocketMQ 的数据表
  rocketmq-table:
    - mall_goods.mall_brand
    - mall_goods.mall_category
