spring:
  # Kafka 配置
  kafka:
    # Kafka 客户端唯一标识 (用于 Kafka 服务端日志记录)
    client-id: ${spring.application.name}
    # Kafka 消费者配置
    consumer:
      # Kafka 服务端地址
      bootstrap-servers: host.docker.internal:9092
      # Kafka 消费者消息反序列化器
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# ElasticSearch 配置
elastic-search:
  host: host.docker.internal
  port: 9200
  # 网络连接策略
  scheme: http

# RocketMQ 配置
rocketmq:
  name-server: host.docker.internal:9876
  # 生产者配置
  producer:
    # 默认生产者组
    group: ${spring.application.name}
