spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/mall_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 微服务配置
  cloud:
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: host.docker.internal:8858

# XXL-JOB 配置
xxl:
  job:
    # 通讯令牌
    accessToken: default_token
    # 调度中心配置
    admin:
      addresses: http://host.docker.internal:8001/xxl-job-admin
    # 执行器配置
    executor:
      appname: ${spring.application.name}
      port: 28082
      logpath: logs/xxl-job/${xxl.job.executor.appname}
      logretentiondays: 10
