spring:
  # Spring Security 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取 JWK 公钥接口
          jwk-set-uri: http://host.docker.internal:${server.port}/mall-security/jwk/jwk-set
  # Redis 配置
  redis:
    host: host.docker.internal
    port: 6379
    password: 123456
    database: 0
