spring:
  profiles:
    active: dev
  servlet:
    # 文件设置
    multipart:
      # 文件上传最大限制
      max-file-size: 100MB
      max-request-size: 100MB

# Feign 配置
feign:
  # Feign 远程方法调用开启 Sentinel 熔断限流
  sentinel:
    enabled: true

# LogBack 配置
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
