spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # 微服务配置
  cloud:
    # Nacos 配置
    nacos:
      # Nacos 注册中心
      discovery:
        server-addr: 127.0.0.1:8848
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: 127.0.0.1:8858

# XXL-JOB 配置
xxl:
  job:
    # 通讯令牌
    accessToken: default_token
    # 调度中心配置
    admin:
      addresses: http://127.0.0.1:8001/xxl-job-admin
    # 执行器配置
    executor:
      appname: ${spring.application.name}
      port: 28082
      logpath: logs/xxl-job/${xxl.job.executor.appname}
      logretentiondays: 10

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # dev 环境打印 SQL 到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
