apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-manager-service
spec:
  type: NodePort
  selector:
    app: mall-manager
  ports:
    - nodePort: 30085
      port: 18085
      targetPort: 18085
      protocol: TCP
