spring:
  profiles:
    active: dev
  servlet:
    # 文件设置
    multipart:
      # 文件上传最大限制
      max-file-size: 100MB
      max-request-size: 100MB

# Feign 配置
feign:
  # 开启 Hystrix
  hystrix:
    enabled: true

# Hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 超时熔断时间 10000 毫秒
            timeoutInMilliseconds: 10000

# MinIO 配置
minio:
  # 服务地址
  endpoint: http://127.0.0.1:9000
  # 文件地址
  file-host: http://127.0.0.1:9000
  # 用户名
  access-key: administrator
  # 密码
  secret-key: 123456789
  # 字符集&编码
  character-encoding: utf-8
  # 下载时的 HTTP Response 内容类型 (强制下载)
  content-type: application/force-download
  # 下载时使用的 HTTP Header Key
  header-key: Content-Disposition
  # 下载时使用的 HTTP Header Value 前缀
  header-value-prefix: attachment;fileName=