apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-security-service
spec:
  type: NodePort
  selector:
    app: mall-security
  ports:
    - nodePort: 30072
      port: 18072
      targetPort: 18072
      protocol: TCP
