spring:
  profiles:
    active: dev
  cloud:
    # 网关配置
    gateway:
      # 服务发现配置
      discovery:
        locator:
          # 使用微服务名称进行定位
          enabled: true
          # 设置服务名称为小写, 默认 false 为大写
          lower-case-service-id: true
      # 路由配置
      routes:
        - id: mall-security-management
          uri: lb://mall-security-management
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: mall-goods
          uri: lb://mall-goods
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=2

# 白名单路径配置
secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/api/security/oauth/token"
