apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-solr-service
spec:
  type: NodePort
  selector:
    app: mall-solr
  ports:
    - nodePort: 30094
      port: 18094
      targetPort: 18094
      protocol: TCP
