apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-admin-service
spec:
  type: NodePort
  selector:
    app: mall-admin
  ports:
    - nodePort: 30075
      port: 18075
      targetPort: 18075
      protocol: TCP
