apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-fastdfs-service
spec:
  type: NodePort
  selector:
    app: mall-fastdfs
  ports:
    - nodePort: 30092
      port: 18092
      targetPort: 18092
      protocol: TCP
