spring:
  profiles:
    active: dev
  servlet:
    # 文件设置
    multipart:
      # 文件上传最大限制
      max-file-size: 100MB
      max-request-size: 100MB

# Feign 配置
feign:
  # 开启 Hystrix
  hystrix:
    enabled: true

# Hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 超时熔断时间 10000 毫秒
            timeoutInMilliseconds: 10000
