apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-gateway-service
spec:
  type: NodePort
  selector:
    app: mall-gateway
  ports:
    - nodePort: 30071
      port: 18071
      targetPort: 18071
      protocol: TCP
