spring:
  # 微服务配置
  cloud:
    # Nacos 配置
    nacos:
      # Nacos 注册中心
      discovery:
        server-addr: 127.0.0.1:8848
    # Sentinel 配置
    sentinel:
      # Sentinel 控制台
      transport:
        dashboard: 127.0.0.1:8858

# FastDFS 配置
fastdfs:
  # 字符集&编码
  character-encoding: utf-8
  # 下载时的 HTTP Response 内容类型 (强制下载)
  content-type: application/force-download
  # 下载时使用的 HTTP Header Key
  header-key: Content-Disposition
  # 下载时使用的 HTTP Header Value 前缀
  header-value-prefix: attachment;fileName=
