apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-eureka-service
spec:
  type: NodePort
  selector:
    app: mall-eureka
  ports:
    - nodePort: 32001
      port: 8761
      targetPort: 8761
      protocol: TCP
