apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-qiniu-service
spec:
  type: NodePort
  selector:
    app: mall-qiniu
  ports:
    - nodePort: 30095
      port: 18095
      targetPort: 18095
      protocol: TCP
