apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-meilisearch-service
spec:
  type: NodePort
  selector:
    app: mall-meilisearch
  ports:
    - nodePort: 30097
      port: 18097
      targetPort: 18097
      protocol: TCP
