apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-id-service
spec:
  type: NodePort
  selector:
    app: mall-id
  ports:
    - nodePort: 30074
      port: 18074
      targetPort: 18074
      protocol: TCP
