apiVersion: v1
kind: Service
metadata:
  namespace: mall
  name: mall-grinder-service
spec:
  type: NodePort
  selector:
    app: mall-grinder
  ports:
    - nodePort: 30011
      port: 18011
      targetPort: 18011
      protocol: TCP
