spring:
  profiles:
    active: dev
  # 自动装配时排除 JDBC 数据源配置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Binlog 数据库监听配置 (监听表配置)
binlog:
  table:
    - mall_user.mall_role
    - mall_user.mall_role_menu
